import { Task, User } from './types'

export const mockUsers: User[] = [
  { id: '1', name: 'John Doe', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John' },
  { id: '2', name: 'Jane Smith', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane' },
  { id: '3', name: 'Mike Johnson', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike' },
  { id: '4', name: 'Sarah Williams', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah' },
]

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Design landing page mockup',
    description: 'Create hero section and feature blocks',
    status: 'pending',
    priority: 'high',
    dueDate: '2026-02-05',
    assignees: [mockUsers[0], mockUsers[1]],
  },
  {
    id: '2',
    title: 'Setup development environment',
    description: 'Configure Docker and dependencies',
    status: 'pending',
    priority: 'normal',
    dueDate: '2026-02-03',
    assignees: [mockUsers[2]],
  },
  {
    id: '3',
    title: 'Implement user authentication',
    description: 'Add login and registration flows',
    status: 'in_progress',
    priority: 'high',
    dueDate: '2026-02-08',
    assignees: [mockUsers[0], mockUsers[2]],
  },
  {
    id: '4',
    title: 'Build REST API endpoints',
    description: 'Create CRUD operations for tasks',
    status: 'in_progress',
    priority: 'high',
    dueDate: '2026-02-06',
    assignees: [mockUsers[3]],
  },
  {
    id: '5',
    title: 'Write unit tests',
    description: 'Cover critical functionality',
    status: 'in_progress',
    priority: 'normal',
    dueDate: '2026-02-10',
    assignees: [mockUsers[1]],
  },
  {
    id: '6',
    title: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions',
    status: 'completed',
    priority: 'normal',
    dueDate: '2026-01-30',
    assignees: [mockUsers[2]],
  },
  {
    id: '7',
    title: 'Database schema design',
    description: 'Define tables and relationships',
    status: 'completed',
    priority: 'high',
    dueDate: '2026-01-28',
    assignees: [mockUsers[0], mockUsers[3]],
  },
  {
    id: '8',
    title: 'Deploy to production',
    description: 'First production deployment',
    status: 'launched',
    priority: 'high',
    dueDate: '2026-01-25',
    assignees: [mockUsers[1], mockUsers[2], mockUsers[3]],
  },
  {
    id: '9',
    title: 'User feedback collection',
    description: 'Gather initial user responses',
    status: 'launched',
    priority: 'normal',
    dueDate: '2026-01-26',
    assignees: [mockUsers[0]],
  },
]
